///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebWordPressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeletePost recording.
    /// </summary>
    [TestModule("d3c9939f-4a9c-4c66-b0ba-0a26ae62285f", ModuleType.Recording, 1)]
    public partial class DeletePost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebWordPressLibraryRepository repository.
        /// </summary>
        public static WebWordPressLibraryRepository repo = WebWordPressLibraryRepository.Instance;

        static DeletePost instance = new DeletePost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeletePost()
        {
            varPostURL = "http://webtest.ranorex.org/";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeletePost Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varPostURL.
        /// </summary>
        [TestVariable("4bc16de1-50a7-44d5-afb2-6d1c869096bc")]
        public string varPostURL
        {
            get { return repo.varPostURL; }
            set { repo.varPostURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate(variable $varPostURL) on item 'WordPress_Demo'.", repo.WordPress_Demo.SelfInfo, new RecordItemIndex(0));
            repo.WordPress_Demo.Self.Navigate(varPostURL);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.RecentPost' at Center.", repo.WordPress_Demo.RecentPostInfo, new RecordItemIndex(1));
            repo.WordPress_Demo.RecentPost.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.EditPost' at Center.", repo.WordPress_Demo.EditPostInfo, new RecordItemIndex(2));
            repo.WordPress_Demo.EditPost.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.MoveToTrash' at Center.", repo.WordPress_Demo.MoveToTrashInfo, new RecordItemIndex(3));
            repo.WordPress_Demo.MoveToTrash.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
