///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebWordPressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetPostURL recording.
    /// </summary>
    [TestModule("a144ff6a-5458-489a-b361-c147c99c84cb", ModuleType.Recording, 1)]
    public partial class GetPostURL : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebWordPressLibraryRepository repository.
        /// </summary>
        public static WebWordPressLibraryRepository repo = WebWordPressLibraryRepository.Instance;

        static GetPostURL instance = new GetPostURL();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetPostURL()
        {
            varPostURL = "http://webtest.ranorex.org";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetPostURL Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varPostURL.
        /// </summary>
        [TestVariable("b1596443-4254-4a51-8f14-21ed0b4103fa")]
        public string varPostURL
        {
            get { return repo.varPostURL; }
            set { repo.varPostURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'WordPress_Demo.SamplePermalink' and assigning its value to variable 'varPostURL'.", repo.WordPress_Demo.SamplePermalinkInfo, new RecordItemIndex(0));
            varPostURL = repo.WordPress_Demo.SamplePermalink.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
