///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebWordPressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateNewPost recording.
    /// </summary>
    [TestModule("b0235fd3-422d-452e-8d02-133e4dffd6e4", ModuleType.Recording, 1)]
    public partial class NavigateNewPost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebWordPressLibraryRepository repository.
        /// </summary>
        public static WebWordPressLibraryRepository repo = WebWordPressLibraryRepository.Instance;

        static NavigateNewPost instance = new NavigateNewPost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateNewPost()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateNewPost Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'WordPress_Demo.Posts'.", repo.WordPress_Demo.PostsInfo, new RecordItemIndex(0));
            repo.WordPress_Demo.Posts.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'WordPress_Demo.Posts' at Center.", repo.WordPress_Demo.PostsInfo, new RecordItemIndex(1));
            repo.WordPress_Demo.Posts.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'WordPress_Demo.AllPosts' at Center.", repo.WordPress_Demo.AllPostsInfo, new RecordItemIndex(2));
            repo.WordPress_Demo.AllPosts.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.AddNew' at Center.", repo.WordPress_Demo.AddNewInfo, new RecordItemIndex(3));
            repo.WordPress_Demo.AddNew.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
