///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebWordPressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PublishNewPost recording.
    /// </summary>
    [TestModule("5c0438e0-4aa8-4cce-9d0d-0adda576c6a7", ModuleType.Recording, 1)]
    public partial class PublishNewPost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebWordPressLibraryRepository repository.
        /// </summary>
        public static WebWordPressLibraryRepository repo = WebWordPressLibraryRepository.Instance;

        static PublishNewPost instance = new PublishNewPost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PublishNewPost()
        {
            varPostTitle = "Ranorex is awesome!";
            varPostContent = "This is a demo-post automated with Ranorex.";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PublishNewPost Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPostContent;

        /// <summary>
        /// Gets or sets the value of variable varPostContent.
        /// </summary>
        [TestVariable("dd605212-15af-4a8f-896c-9dcf52b443fd")]
        public string varPostContent
        {
            get { return _varPostContent; }
            set { _varPostContent = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varPostTitle.
        /// </summary>
        [TestVariable("d33e7490-f575-476c-8366-4f40a23db2b8")]
        public string varPostTitle
        {
            get { return repo.varPostTitle; }
            set { repo.varPostTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.Title' at Center.", repo.WordPress_Demo.TitleInfo, new RecordItemIndex(0));
            repo.WordPress_Demo.Title.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$varPostTitle' on item 'WordPress_Demo.Title'.", repo.WordPress_Demo.TitleInfo, new RecordItemIndex(1));
            repo.WordPress_Demo.Title.Element.SetAttributeValue("Value", varPostTitle);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.Content' at 199;67.", repo.WordPress_Demo.ContentInfo, new RecordItemIndex(2));
            repo.WordPress_Demo.Content.Click("199;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$varPostContent' on item 'WordPress_Demo.Content'.", repo.WordPress_Demo.ContentInfo, new RecordItemIndex(3));
            repo.WordPress_Demo.Content.Element.SetAttributeValue("TagValue", varPostContent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WordPress_Demo.Publish' at 43;14.", repo.WordPress_Demo.PublishInfo, new RecordItemIndex(4));
            repo.WordPress_Demo.Publish.Click("43;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
