///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebWordPressLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatePost recording.
    /// </summary>
    [TestModule("fc856961-94e1-4ead-8db8-e0eac61124f6", ModuleType.Recording, 1)]
    public partial class ValidatePost : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebWordPressLibraryRepository repository.
        /// </summary>
        public static WebWordPressLibraryRepository repo = WebWordPressLibraryRepository.Instance;

        static ValidatePost instance = new ValidatePost();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatePost()
        {
            varPostURL = "http://webtest.ranorex.org/";
            varPostTitle = "Ranorex is awesome!";
            varPostContent = "This is a demo-post automated with Ranorex.";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatePost Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPostContent;

        /// <summary>
        /// Gets or sets the value of variable varPostContent.
        /// </summary>
        [TestVariable("1a970251-5f1d-4c3b-bd06-dde472fffa3a")]
        public string varPostContent
        {
            get { return _varPostContent; }
            set { _varPostContent = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varPostURL.
        /// </summary>
        [TestVariable("28d850b1-fee7-4ff4-9734-a496c266a7c2")]
        public string varPostURL
        {
            get { return repo.varPostURL; }
            set { repo.varPostURL = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varPostTitle.
        /// </summary>
        [TestVariable("d34372ff-4574-4cdb-a34f-a2c11289d06d")]
        public string varPostTitle
        {
            get { return repo.varPostTitle; }
            set { repo.varPostTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate(variable $varPostURL) on item 'WordPress_Demo'.", repo.WordPress_Demo.SelfInfo, new RecordItemIndex(0));
            repo.WordPress_Demo.Self.Navigate(varPostURL);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varPostTitle) on item 'WordPress_Demo.Pagetitle'.", repo.WordPress_Demo.PagetitleInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.WordPress_Demo.PagetitleInfo, "InnerText", varPostTitle);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'WordPress_Demo.Pagetitle'.", repo.WordPress_Demo.PagetitleInfo, new RecordItemIndex(2));
            repo.WordPress_Demo.Pagetitle.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPress_Demo.Pagetitle, false, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varPostContent) on item 'WordPress_Demo.PostContent'.", repo.WordPress_Demo.PostContentInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.WordPress_Demo.PostContentInfo, "InnerText", varPostContent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'WordPress_Demo.PostContent'.", repo.WordPress_Demo.PostContentInfo, new RecordItemIndex(5));
            repo.WordPress_Demo.PostContent.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.WordPress_Demo.PostContent, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
